### ISSUE TITLE
Idea: Pass through onClick prop to the rendered component

### ISSUE THREAD

**Issue by jasepellerin** [gilbarbara/react-inlinesvg#97] opened 2018-06-10 17:00 UTC
>Expected behavior
Adding an onClick prop to an inlinesvg component would catch clicks targeting the rendered element.

>Actual behavior
Adding an onClick prop to an inlinesvg component doesn't do anything.

We use this library a good amount, and we typically end up wrapping the inlinesvg in some other wrapper to handle click events. It would be nice if we could simply pass in an optional onClick prop and not need the wrapper.

**Comment by nickmccurdy** [comment] 2019-01-16 21:45
Seems like a duplicate of #105 which is more general

**Comment by gilbarbara** [comment] 2019-01-28 00:02
Hey

There is a new version with support for title, description and custom props.
Can you please try it? `npm i react-inlinesvg@next`
There are a few changes in props, you can check it [here](https://github.com/gilbarbara/react-inlinesvg/tree/next)

**Closed** 2019-07-18 18:32 UTC
