### ISSUE TITLE
Uniquify class names

### ISSUE THREAD

**Issue by robrechtme** [gilbarbara/react-inlinesvg#93] opened 2018-03-29 16:23 UTC
My SVGs are filled with a `style` tag inside, and some general classnames to choose a fill color.
This causes conflicts when multiple SVGs are loaded on one page.

**Comment by gilbarbara** [comment] 2018-03-29 16:28
Meaning?

**Comment by RobrechtM** [comment] 2018-03-29 17:13
Duplicate of #83 , sorry. 
This means that one SVG its fill color is overwritten by the other SVG. Obviously you can just pick better classnames for each color, but Illustrator exports SVGs by default like the example in #83. 

I thought uniquifying the classnames (in the elements but also in the `style` tag) would be a good solution. Inlining all CSS of each SVG is also a possibility.

**Comment by gilbarbara** [comment] 2018-03-29 18:08
So `uniquifyIDs` won't help in this case, right?
This isn't something I want to support since Illustrator is really bad at SVG exporting. It would just bloat the library.

**Closed as completed** 2018-03-29 20:18 UTC
