### ISSUE TITLE
Issue with React v17 and TypeScript

### ISSUE THREAD

**Issue by itsmdsameerkhan** [gilbarbara/react-inlinesvg#187] opened 2022-05-15 07:49 UTC
'SVG' cannot be used as a JSX component.
  Its instance type 'InlineSVG' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.

**Comment by hesan-aminiloo** [comment] 2022-05-15 16:13
Same here

**Comment by gilbarbara** [comment] 2022-05-15 17:42
Duplicate of #181

**Closed by gilbarbara** 2022-05-15 17:42 UTC

**Comment by huytq03** [comment] 2022-05-20 09:28
why this issue has closed like #181  but none of them have a solution?

**Comment by gilbarbara** [comment] 2022-05-20 20:34
@huytq03

Because it is not a problem with this library.
Did you check [this](https://github.com/gilbarbara/react-inlinesvg/discussions/186)?

**Comment by huytq03** [comment] 2022-05-21 09:12
> @huytq03
> 
> Because it is not a problem with this library. Did you check [this](https://github.com/gilbarbara/react-inlinesvg/discussions/186)?

fixed. tks
